env:
  node: true
  mocha: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - off
    - 2
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - never
